### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by bd82** [aetherised/lexdoc#1]
Hello.

This concise API for creating Chevrotain Lexers looks great. 👍 

I was think that perhaps instead of having a direct dependency to Chevrotain.
It may be better to use a peer-dependency.

```javascript
const chevrotain = require("chevrotain")
// expose a factory function that accepts the chevrotain object.
const LD = require('lexdoc')(chevrotain)
```

This is because:
1. Chevrotain also supports [custom Parser APIs](http://sap.github.io/chevrotain/docs/guide/custom_apis.html) so if each custom API ("plugin") has a **direct** dependency we are going to have conflicts...
2. Also I'm guessing lexdoc uses a limited subset of Chevrotain's APIs, so it should not be too hard
   to implement a **runtime** validator that inspects all the APIs that are required are provided.

This would reduce the need to track Chevrotain versions (perhaps only major versions would require modifications), and allow supporting a range of versions of Chevrotain.

**Comment by 0E9B061F** [comment]
Hello! Thanks for the compliment, I'm glad you think so.

I think this is a good suggestion and dependency injection would be a better approach. I threw Lexdoc together pretty quickly without giving much thought to how it fits into the bigger scheme of things, and it would certainly be easier to maintain this way. I'll get to work on it shortly.

**Comment by 0E9B061F** [comment]
Implemented. Thanks for the suggestion (and all your work on Chevrotain itself).

**Comment by bd82** [comment]
👍
